openapi: "3.0.3"
info:
  version: "1.0.0"
  title: Pepe Chat
  description: Open-Source Distributed Chat Server
paths:
  /login:
    post:
      summary: Log into your account
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDetails"
      responses:
        200:
          description: Logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        403:
          description: Account does not exist or invalid password
  /register:
    post:
      summary: Create a new account
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDetails"
      responses:
        201:
          description: Successfully created account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginSuccess"
        400:
          description: Password too insecure
        409:
          description: Username already exists
  /channels:
    get:
      description: Get all channels
      responses:
        200:
          description: Successfully retreived channel
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Channel"
  /users:
    description: Get users of a server
    get:
      responses:
        200:
          description: All users on this server
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"


  /users/me:
    description: Get Info about myself
    get:
      responses:
        200:
          description: The user logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          $ref: "#/components/responses/401"

components:
  schemas:
    LoginDetails:
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    LoginSuccess:
      properties:
        token:
          type: string
    Channel:
      required:
        - name
        - id
      properties:
        name:
          type: string
        id:
          type: string
    User:
      properties:
        username:
          type: string
          required: true
        id:
          type: string
          readOnly: true
          required: true
        online:
          type: boolean

  responses:
    401:
      description: Unauthorized to access server
      content:
        text/plain:
          schema:
            enum:
              - no-token
              - token-expired
              - invalid-token