spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pepechat
    username: pepe
    password: feelsgoodman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false